# Hyperledger Fabric Orderer Configuration
General:
  # Ledger Type
  LedgerType: file
  
  # Listen address
  ListenAddress: 0.0.0.0
  ListenPort: 7050
  
  # TLS configuration
  TLS:
    Enabled: true
    PrivateKey: /var/hyperledger/orderer/tls/server.key
    Certificate: /var/hyperledger/orderer/tls/server.crt
    RootCAs:
      - /var/hyperledger/orderer/tls/ca.crt
    ClientAuthRequired: false
    ClientRootCAs:
      - /var/hyperledger/orderer/tls/ca.crt
      
  # Cluster configuration
  Cluster:
    ClientCertificate: /var/hyperledger/orderer/tls/server.crt
    ClientPrivateKey: /var/hyperledger/orderer/tls/server.key
    RootCAs:
      - /var/hyperledger/orderer/tls/ca.crt
      
  # Keepalive configuration
  Keepalive:
    ServerMinInterval: 60s
    ServerInterval: 7200s
    ServerTimeout: 20s
    
  # Connection timeout
  ConnectionTimeout: 0s
  
  # Max message size
  MaxRecvMsgSize: 104857600
  MaxSendMsgSize: 104857600
  
  # Local MSP
  LocalMSPDir: /var/hyperledger/orderer/msp
  LocalMSPID: OrdererMSP
  
  # Profile
  Profile:
    Enabled: false
    Address: 0.0.0.0:6060
    
  # BCCSP (Blockchain Crypto Service Provider)
  BCCSP:
    Default: SW
    SW:
      Hash: SHA2
      Security: 256
      FileKeyStore:
        KeyStore:
        
  # Authentication
  Authentication:
    TimeWindow: 15m

# File ledger configuration
FileLedger:
  Location: /var/hyperledger/production/orderer
  Prefix: hyperledger-fabric-ordererledger

# RAM ledger configuration (for testing)
RAMLedger:
  HistorySize: 1000

# Kafka configuration (if using Kafka consensus)
Kafka:
  Retry:
    ShortInterval: 5s
    ShortTotal: 10m
    LongInterval: 5m
    LongTotal: 12h
    NetworkTimeouts:
      DialTimeout: 10s
      ReadTimeout: 10s
      WriteTimeout: 10s
    Metadata:
      RetryBackoff: 250ms
      RetryMax: 3
    Producer:
      RetryBackoff: 100ms
      RetryMax: 3
    Consumer:
      RetryBackoff: 2s
  Topic:
    ReplicationFactor: 3
  Verbose: false
  Version:

# Debug configuration
Debug:
  BroadcastTraceDir:
  DeliverTraceDir:

# Operations configuration
Operations:
  ListenAddress: 0.0.0.0:8443
  TLS:
    Enabled: false
    Certificate:
    PrivateKey:
    ClientAuthRequired: false
    ClientRootCAs: []

# Metrics configuration
Metrics:
  Provider: prometheus
  Statsd:
    Network: udp
    Address: 127.0.0.1:8125
    WriteInterval: 30s
    Prefix:

# Consensus configuration
Consensus:
  WALDir: /var/hyperledger/production/orderer/etcdraft/wal
  SnapDir: /var/hyperledger/production/orderer/etcdraft/snapshot

# Channel participation
ChannelParticipation:
  Enabled: true
  MaxRequestBodySize: 1048576

# Admin configuration
Admin:
  ListenAddress: 0.0.0.0:7053
  TLS:
    Enabled: true
    Certificate: /var/hyperledger/orderer/tls/server.crt
    PrivateKey: /var/hyperledger/orderer/tls/server.key
    ClientAuthRequired: false
    ClientRootCAs:
      - /var/hyperledger/orderer/tls/ca.crt