version: '3.8'

services:
  besu-node1:
    image: hyperledger/besu:latest
    container_name: besu-node1
    command:
      - --data-path=/opt/besu/data
      - --genesis-file=/opt/besu/genesis.json
      - --rpc-http-enabled
      - --rpc-http-host=0.0.0.0
      - --rpc-http-port=8545
      - --rpc-http-cors-origins=*
      - --rpc-ws-enabled
      - --rpc-ws-host=0.0.0.0
      - --rpc-ws-port=8546
      - --consensus-algorithm=ibft2
      - --network-id=2018
      - --min-gas-price=0
      - --miner-enabled
      - --miner-coinbase=0x627306090abab3a6e1400e9345bc60c78a8bef57
    volumes:
      - ./besu/genesis.json:/opt/besu/genesis.json
      - besu1_data:/opt/besu/data
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
    networks:
      - besu-network
    environment:
      - JAVA_OPTS=-Xmx2g

  besu-node2:
    image: hyperledger/besu:latest
    container_name: besu-node2
    command:
      - --data-path=/opt/besu/data
      - --genesis-file=/opt/besu/genesis.json
      - --consensus-algorithm=ibft2
      - --network-id=2018
      - --min-gas-price=0
      - --miner-enabled
      - --miner-coinbase=0xf17f52151ebef6c7334fad080c5704d77216b732
      - --bootnodes=enode://besu-node1@besu-node1:30303
    volumes:
      - ./besu/genesis.json:/opt/besu/genesis.json
      - besu2_data:/opt/besu/data
    depends_on:
      - besu-node1
    networks:
      - besu-network
    environment:
      - JAVA_OPTS=-Xmx2g

  besu-node3:
    image: hyperledger/besu:latest
    container_name: besu-node3
    command:
      - --data-path=/opt/besu/data
      - --genesis-file=/opt/besu/genesis.json
      - --consensus-algorithm=ibft2
      - --network-id=2018
      - --min-gas-price=0
      - --miner-enabled
      - --miner-coinbase=0xc5fdf4076b8f3a5357c5e395ab970b5b54098fef
      - --bootnodes=enode://besu-node1@besu-node1:30303
    volumes:
      - ./besu/genesis.json:/opt/besu/genesis.json
      - besu3_data:/opt/besu/data
    depends_on:
      - besu-node1
    networks:
      - besu-network
    environment:
      - JAVA_OPTS=-Xmx2g

  besu-node4:
    image: hyperledger/besu:latest
    container_name: besu-node4
    command:
      - --data-path=/opt/besu/data
      - --genesis-file=/opt/besu/genesis.json
      - --consensus-algorithm=ibft2
      - --network-id=2018
      - --min-gas-price=0
      - --miner-enabled
      - --miner-coinbase=0x821aea9a577a9b44299b9c15c88cf3087f3b5544
      - --bootnodes=enode://besu-node1@besu-node1:30303
    volumes:
      - ./besu/genesis.json:/opt/besu/genesis.json
      - besu4_data:/opt/besu/data
    depends_on:
      - besu-node1
    networks:
      - besu-network
    environment:
      - JAVA_OPTS=-Xmx2g

volumes:
  besu1_data:
  besu2_data:
  besu3_data:
  besu4_data:

networks:
  besu-network:
    driver: bridge